version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: financial-tracker-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_INTERNAL_PORT}"
    networks:
      - ${DATABASE_NETWORK_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  ${DATABASE_NETWORK_NAME}:
    external: true

volumes:
  db_data: