version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: financial-tracker-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - ${NETWORK_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  fintrack-network:
    external: true

volumes:
  db_data: