version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: financial-tracker-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financial_tracker
    ports:
      - "5432:5432"
    networks:
      - fintrack-network
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  fintrack-network:
    external: true

volumes:
  db_data:

